name: Check Env Secrets
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment"
        required: true
        type: choice
        options: [DEV, SIT, UAT, PPRD, PRD]

jobs:
  check:
    environment: ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Confirm required secrets are present
        env:
          A: ${{ secrets.SF_ACCOUNT }}
          U: ${{ secrets.SF_USER }}
          P: ${{ secrets.SF_PWD }}  
          R: ${{ secrets.SF_ROLE }}
          W: ${{ secrets.SF_WH }}
          D: ${{ secrets.SF_DB }}
        run: |
          missing=0
          for n in A U P R W D; do
            if [ -z "${!n}" ]; then echo "❌ Missing secret var $n"; missing=1; fi
          done
          if [ "$missing" -ne 0 ]; then exit 1; fi
          echo "✅ All required secrets are present for ${{ inputs.target_env }}"
